# Generated by Django 5.0.6 on 2024-05-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Materi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("1", "Grade 1"),
                            ("2", "Grade 2"),
                            ("3", "Grade 3"),
                            ("4", "Grade 4"),
                            ("5", "Grade 5"),
                            ("6", "Grade 6"),
                        ],
                        max_length=1,
                    ),
                ),
                ("file", models.FileField(upload_to="materi_files/")),
            ],
        ),
    ]
